use_frameworks!
install! 'cocoapods', :share_schemes_for_development_pods => true

platform :ios, '13.0'

target 'JacquardSDK_Example' do

  pod 'JacquardSDK', :path => '../', :testspecs => ['Tests']

  pod 'MaterialComponents'
  pod 'SVProgressHUD'
  pod 'Starling', :git => 'https://github.com/matthewreagan/Starling.git', :commit => 'bf7fb2be59863b4eae8f61694c30b53107135ea1'

  pod 'Charts'

  target 'JacquardSDK_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
