use_frameworks!
install! 'cocoapods', :share_schemes_for_development_pods => true

platform :ios, '13.0'

target 'JacquardSDK_Example' do

  pod 'JacquardSDK', :podspec => '../JacquardSDK.podspec'

  pod 'ProgressHUD', '~> 13'
  pod 'MaterialComponents'
  pod 'Starling', :git => 'https://github.com/matthewreagan/Starling.git', :commit => 'bf7fb2be59863b4eae8f61694c30b53107135ea1'
  
  target 'JacquardSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.select { |target| target.name == "SwiftProtobuf" }.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
